---
name: Condicionales
locale: es
type: learning
beta: false
teacher_info: 'Los ejercicios 7 y 8 están basados en un mismo contexto, por lo que
  hay una serie de datos del código extra que están repetidos en ambos. Si querés
  modificar alguno de ellos, asegurate de también modificarlo en el otro :sweat_smile:'
language: javascript
id_format: "%05d"
order:
- 13
- 1
- 2
- 15
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
